# apps/staging/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../base/podinfo
patches:
  - path: podinfo-values.yml
    target:
      kind: HelmRelease